# Generated by Django 6.0.2 on 2026-02-14 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_caller_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caller',
            name='mobile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='c', to='myapp.mobile'),
        ),
    ]
