# Generated by Django 6.0.2 on 2026-02-14 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_caller_mobile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mobile',
            new_name='car',
        ),
        migrations.CreateModel(
            name='fuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('mobile', models.ManyToManyField(related_name='c', to='myapp.car')),
            ],
        ),
        migrations.DeleteModel(
            name='Caller',
        ),
    ]
