# Generated by Django 6.0.1 on 2026-01-13 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='audio',
        ),
        migrations.RemoveField(
            model_name='student',
            name='video',
        ),
    ]
