# Generated by Django 6.0.2 on 2026-02-10 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adhaar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adharr_no', models.IntegerField()),
                ('create_date', models.DateField(auto_now_add=True)),
                ('create_by', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Stu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('contact', models.IntegerField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('a_no', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.adhaar')),
            ],
        ),
    ]
