# Generated by Django 6.0.2 on 2026-02-11 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stu',
            name='a_no',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='jatin', to='myapp.adhaar'),
        ),
    ]
