# Generated by Django 6.0.2 on 2026-02-12 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_stu_a_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stu',
            name='a_no',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.adhaar'),
        ),
    ]
