# Generated by Django 6.0.3 on 2026-03-16 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_officer_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officer',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
