# Generated by Django 6.0.2 on 2026-02-20 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_19', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=20)),
            ],
        ),
    ]
