# Generated by Django 6.0.1 on 2026-02-18 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_name', models.CharField(blank=True, max_length=50, null=True)),
                ('dept_code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('dept_head', models.CharField(blank=True, max_length=50, null=True)),
                ('dept_budget', models.CharField(blank=True, max_length=50, null=True)),
                ('dept_desc', models.CharField(blank=True, max_length=50, null=True)),
                ('dept_emp', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='emp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('img', models.ImageField(upload_to='profile/')),
                ('adhaar', models.ImageField(upload_to='adhaar/')),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('mobile', models.CharField(max_length=10)),
                ('DOB', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('others', 'Other')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254)),
                ('Query', models.TextField()),
                ('department', models.CharField(max_length=50)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('admin_rep', models.CharField(blank=True)),
            ],
        ),
    ]
