# Generated by Django 6.0.1 on 2026-02-19 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_emp_dept_emp_edu_alter_emp_dob_alter_emp_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp',
            name='dept',
            field=models.OneToOneField(blank=True, max_length=10, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.dep'),
        ),
    ]
