# Generated by Django 6.0.1 on 2026-02-19 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_emp_dept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp',
            name='dept',
            field=models.ForeignKey(blank=True, max_length=20, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.dep'),
        ),
    ]
