# Generated by Django 6.0.1 on 2026-02-08 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_query_query'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp',
            name='img',
            field=models.ImageField(upload_to='profile/'),
        ),
    ]
